name: Save DataFrame

on:
  push:
    branches: [main]

jobs:
  save_dataframe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Install Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Libraries
        run: |
          pip install pandas
          pip install pyarrow
      - name: Create and Save DataFrame
        run: |
          python save_dataframe.py
      - name: Commit and Push Changes
        run: |
          git add data.csv  # Replace with your chosen file format
          git commit -m "Saved DataFrame"
          git push