# This is a basic workflow to help you get started with Actions

name: triggers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: 
      - '**.py'
  # issues:
  #   types:
  #     - labeled

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        default: Python
        required: true
        type: choice
        options: 
          - Python
          - JavaScript
      nombre:
        description: 'Tu nombre'
        required: true
        default: Elefante
        type: string
    schedule:
      - cron: '30 13 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Definir la variable nombre para que la pase al siguiente paso
      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      # Definir la variable lenguaje
      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      # Runs script
      - name: Correr script
        run: python hola_lenguaje.py

  # This workflow contains a single job called "build" you can change
  build:

    # Conditional for workflow dispatch
    if: ${{ github.event_name != 'workflow_dispatch' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Definir la variable nombre para que la pase al siguiente paso
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      # Runs script
      - name: Correr python
        run: python hola_mundo.py